#!/usr/bin/env python3
"""
Deploy Agentic Glue ETL Pipeline to Google Cloud Composer (Airflow).

This script generates and deploys an Airflow DAG that orchestrates
the Bronze → Silver → Gold pipeline on GCP Dataproc.

Usage:
    python scripts/deploy_to_cloud_composer.py \
        --project my-gcp-project \
        --location us-central1 \
        --environment etl-prod \
        --dag-name agentic_etl_dag \
        --schedule "0 2 * * *"

    python scripts/deploy_to_cloud_composer.py \
        --project my-gcp-project \
        --location us-central1 \
        --environment etl-prod \
        --dag-name agentic_etl_dag \
        --update
"""

import os
import sys
import json
import argparse
import subprocess
import tempfile
from pathlib import Path
from datetime import datetime
from typing import List, Dict, Optional

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from config.settings import config


class CloudComposerDeployer:
    """Handles deployment of Airflow DAGs to Cloud Composer."""
    
    def __init__(self,
                 project: str,
                 location: str = "us-central1",
                 environment: str = "etl-prod"):
        """
        Initialize deployer.
        
        Args:
            project: GCP project ID
            location: GCP region
            environment: Cloud Composer environment name
        """
        self.project = project
        self.location = location
        self.environment = environment
        self.project_root = Path(__file__).parent.parent
        
        # GCP environment variables for Airflow
        self.env_vars = {
            "GROQ_API_KEY": os.getenv("GROQ_API_KEY", ""),
            "GCP_PROJECT": project,
            "GCP_REGION": location,
            "DATAPROC_CLUSTER": "etl-cluster",
            "GCS_BUCKET": "my-data-lake",
            "BIGQUERY_DATASET": "gold_analytics",
        }
    
    def check_gcloud_cli(self) -> bool:
        """Verify gcloud CLI is installed."""
        try:
            result = subprocess.run(
                ["gcloud", "--version"],
                capture_output=True,
                text=True,
                timeout=5
            )
            return result.returncode == 0
        except (FileNotFoundError, subprocess.TimeoutExpired):
            print("❌ gcloud CLI not found. Install: https://cloud.google.com/sdk/docs/install")
            return False
    
    def check_composer_environment(self) -> bool:
        """Check if Cloud Composer environment exists."""
        cmd = [
            "gcloud", "composer", "environments", "describe",
            self.environment,
            "--location", self.location,
            "--project", self.project,
            "--format=json"
        ]
        result = subprocess.run(cmd, capture_output=True, text=True)
        
        if result.returncode != 0:
            print(f"❌ Cloud Composer environment '{self.environment}' not found")
            print(f"   Create it with:")
            print(f"   gcloud composer environments create {self.environment} --location {self.location} --project {self.project}")
            return False
        
        try:
            data = json.loads(result.stdout)
            gcs_bucket = data.get("config", {}).get("dagGcsPrefix", "")
            print(f"✅ Cloud Composer environment found: {self.environment}")
            print(f"   DAG bucket: {gcs_bucket}")
            return True
        except:
            print("❌ Failed to parse environment details")
            return False
    
    def generate_dag(self, dag_name: str, schedule_interval: str = "0 2 * * *") -> str:
        """
        Generate Airflow DAG for the ETL pipeline.
        
        Returns:
            DAG content as string
        """
        dag_content = f'''"""
Airflow DAG for Agentic ETL Pipeline - GCP Cloud Composer.

Generated by agentic-glue-etl deployment script.
"""

from datetime import datetime, timedelta
from airflow import DAG
from airflow.providers.google.cloud.operators.dataproc import (
    DataprocSubmitJobOperator,
    DataprocCreateClusterOperator,
    DataprocDeleteClusterOperator,
)
from airflow.providers.google.cloud.operators.bigquery import (
    BigQueryInsertJobOperator,
)
from airflow.providers.google.cloud.sensors.dataproc import (
    DataprocJobSensor,
)
from airflow.operators.python import PythonOperator
from airflow.utils.dates import days_ago

# Default arguments
default_args = {{
    "owner": "data-engineering",
    "depends_on_past": False,
    "email_on_failure": True,
    "email_on_retry": False,
    "email": ["data-eng@example.com"],
    "retries": 3,
    "retry_delay": timedelta(minutes=5),
    "start_date": days_ago(1),
    "project_id": "{self.project}",
    "region": "{self.location}",
}}

# Cluster configuration
CLUSTER_NAME = "etl-cluster-{{{{ ds_nodash }}}}"
CLUSTER_CONFIG = {{
    "projectId": "{self.project}",
    "region": "{self.location}",
    "cluster": {{
        "clusterName": CLUSTER_NAME,
        "config": {{
            "masterConfig": {{
                "machineTypeUri": "n1-standard-4",
                "diskConfig": {{"bootDiskSizeGb": 100}}
            }},
            "workerConfig": {{
                "machineTypeUri": "n1-standard-4",
                "diskConfig": {{"bootDiskSizeGb": 100}},
                "numInstances": 2
            }},
            "softwareConfig": {{
                "imageVersion": "2.1"
            }},
            "gceClusterConfig": {{
                "serviceAccountScopes": [
                    "https://www.googleapis.com/auth/cloud-platform"
                ]
            }}
        }}
    }}
}}

# Spark job configuration
BRONZE_JOB = {{
    "reference": {{"jobId": "bronze-{{{{ ds_nodash }}}}"}},
    "placement": {{"clusterName": CLUSTER_NAME}},
    "sparkJob": {{
        "mainClass": "org.apache.spark.deploy.PythonRunner",
        "args": [
            "gs://{{{{ var.value.get('GCS_SCRIPTS_BUCKET') }}}}/dataproc_pipeline.py",
            "--layer", "bronze"
        ],
        "jarFileUris": [
            "gs://spark-lib/bigquery/spark-bigquery-latest_2.12.jar"
        ],
        "properties": {{
            "spark.sql.adaptive.enabled": "true",
            "spark.sql.adaptive.coalescePartitions.enabled": "true",
            "spark.sql.execution.arrow.pyspark.enabled": "true"
        }}
    }}
}}

SILVER_JOB = {{
    "reference": {{"jobId": "silver-{{{{ ds_nodash }}}}"}},
    "placement": {{"clusterName": CLUSTER_NAME}},
    "sparkJob": {{
        "mainClass": "org.apache.spark.deploy.PythonRunner",
        "args": [
            "gs://{{{{ var.value.get('GCS_SCRIPTS_BUCKET') }}}}/dataproc_pipeline.py",
            "--layer", "silver"
        ],
        "jarFileUris": [
            "gs://spark-lib/bigquery/spark-bigquery-latest_2.12.jar"
        ],
        "properties": {{
            "spark.sql.adaptive.enabled": "true",
            "spark.sql.adaptive.coalescePartitions.enabled": "true",
            "spark.sql.execution.arrow.pyspark.enabled": "true"
        }}
    }}
}}

GOLD_JOB = {{
    "reference": {{"jobId": "gold-{{{{ ds_nodash }}}}"}},
    "placement": {{"clusterName": CLUSTER_NAME}},
    "sparkJob": {{
        "mainClass": "org.apache.spark.deploy.PythonRunner",
        "args": [
            "gs://{{{{ var.value.get('GCS_SCRIPTS_BUCKET') }}}}/dataproc_pipeline.py",
            "--layer", "gold"
        ],
        "jarFileUris": [
            "gs://spark-lib/bigquery/spark-bigquery-latest_2.12.jar"
        ],
        "properties": {{
            "spark.sql.adaptive.enabled": "true",
            "spark.sql.adaptive.coalescePartitions.enabled": "true",
            "spark.sql.execution.arrow.pyspark.enabled": "true"
        }}
    }}
}}

with DAG(
    dag_id="{dag_name}",
    default_args=default_args,
    description="Agentic ETL Pipeline - Bronze → Silver → Gold",
    schedule_interval="{schedule_interval}",
    catchup=False,
    max_active_runs=1,
    tags=["etl", "agentic", "dataproc", "bigquery"],
) as dag:
    
    # 1. Create Dataproc cluster (if using ephemeral)
    # Uncomment for ephemeral cluster pattern
    # create_cluster = DataprocCreateClusterOperator(
    #     task_id="create_cluster",
    #     cluster_name=CLUSTER_NAME,
    #     project_id="{self.project}",
    #     cluster_config=CLUSTER_CONFIG,
    # )
    
    # 2. Submit Bronze job
    bronze_task = DataprocSubmitJobOperator(
        task_id="bronze_layer",
        job=BRONZE_JOB,
        region="{self.location}",
        project_id="{self.project}",
    )
    
    # 3. Wait for Bronze completion
    bronze_sensor = DataprocJobSensor(
        task_id="bronze_sensor",
        job_id=BRONZE_JOB["reference"]["jobId"],
        region="{self.location}",
        project_id="{self.project}",
    )
    
    # 4. Submit Silver job
    silver_task = DataprocSubmitJobOperator(
        task_id="silver_layer",
        job=SILVER_JOB,
        region="{self.location}",
        project_id="{self.project}",
    )
    
    # 5. Wait for Silver completion
    silver_sensor = DataprocJobSensor(
        task_id="silver_sensor",
        job_id=SILVER_JOB["reference"]["jobId"],
        region="{self.location}",
        project_id="{self.project}",
    )
    
    # 6. Submit Gold job
    gold_task = DataprocSubmitJobOperator(
        task_id="gold_layer",
        job=GOLD_JOB,
        region="{self.location}",
        project_id="{self.project}",
    )
    
    # 7. Wait for Gold completion
    gold_sensor = DataprocJobSensor(
        task_id="gold_sensor",
        job_id=GOLD_JOB["reference"]["jobId"],
        region="{self.location}",
        project_id="{self.project}",
    )
    
    # 8. Delete cluster (if using ephemeral)
    # Uncomment for ephemeral cluster pattern
    # delete_cluster = DataprocDeleteClusterOperator(
    #     task_id="delete_cluster",
    #     cluster_name=CLUSTER_NAME,
    #     project_id="{self.project}",
    #     region="{self.location}",
    # )
    
    # Task dependencies
    bronze_task >> bronze_sensor >> silver_task >> silver_sensor >> gold_task >> gold_sensor
    
    # For ephemeral cluster:
    # create_cluster >> bronze_task >> bronze_sensor >> silver_task >> silver_sensor >> gold_task >> gold_sensor >> delete_cluster

'''
        
        return dag_content
    
    def save_dag_file(self, dag_name: str, schedule_interval: str = "0 2 * * *") -> str:
        """Save DAG to file."""
        dag_content = self.generate_dag(dag_name, schedule_interval)
        
        dag_file = self.project_root / "infra" / "gcp" / f"{dag_name}.py"
        dag_file.parent.mkdir(parents=True, exist_ok=True)
        
        with open(dag_file, 'w') as f:
            f.write(dag_content)
        
        print(f"✅ DAG saved to: {dag_file}")
        return str(dag_file)
    
    def upload_dag_to_composer(self, dag_file: str) -> bool:
        """
        Upload DAG file to Cloud Composer's GCS bucket.
        """
        print(f"\n☁️  Uploading DAG to Cloud Composer: {self.environment}")
        
        # Get the DAG bucket path
        cmd = [
            "gcloud", "composer", "environments", "describe",
            self.environment,
            "--location", self.location,
            "--project", self.project,
            "--format=json"
        ]
        
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            print(f"❌ Failed to get environment details: {result.stderr}")
            return False
        
        try:
            data = json.loads(result.stdout)
            gcs_bucket = data.get("config", {}).get("dagGcsPrefix", "")
            if not gcs_bucket:
                print("❌ Could not find DAG bucket")
                return False
        except:
            print("❌ Failed to parse environment details")
            return False
        
        # Upload DAG file
        upload_cmd = [
            "gcloud", "storage", "cp",
            dag_file,
            f"{gcs_bucket}/",
            "--project", self.project
        ]
        
        result = subprocess.run(upload_cmd, capture_output=True, text=True)
        
        if result.returncode != 0:
            print(f"❌ Upload failed: {result.stderr}")
            return False
        
        print(f"✅ DAG uploaded to: {gcs_bucket}/")
        return True
    
    def update_env_vars(self) -> bool:
        """
        Update Cloud Composer environment variables for the pipeline.
        """
        print(f"\n🔧 Updating Cloud Composer environment variables...")
        
        # Build update command
        env_vars_str = ",".join([f"{k}={v}" for k, v in self.env_vars.items() if v])
        
        cmd = [
            "gcloud", "composer", "environments", "update",
            self.environment,
            "--location", self.location,
            "--project", self.project,
            "--update-env-variables", env_vars_str
        ]
        
        result = subprocess.run(cmd, capture_output=True, text=True)
        
        if result.returncode != 0:
            print(f"⚠️  Failed to update environment variables: {result.stderr}")
            print("   You can set them manually in the GCP Console.")
            return False
        
        print(f"✅ Environment variables updated")
        return True
    
    def deploy(self,
               dag_name: str = "agentic_etl_dag",
               schedule_interval: str = "0 2 * * *") -> bool:
        """
        Complete deployment workflow.
        """
        print("\n" + "="*60)
        print("🚀 Starting Cloud Composer Deployment")
        print("="*60)
        
        # Check gcloud CLI
        if not self.check_gcloud_cli():
            return False
        
        # Check Cloud Composer environment
        if not self.check_composer_environment():
            return False
        
        # Generate DAG
        dag_file = self.save_dag_file(dag_name, schedule_interval)
        
        # Upload DAG to Composer
        if not self.upload_dag_to_composer(dag_file):
            return False
        
        # Update environment variables
        self.update_env_vars()
        
        print("\n" + "="*60)
        print("🎉 Deployment Complete!")
        print("="*60)
        print(f"\nNext steps:")
        print(f"1. Check DAG in Airflow UI:")
        print(f"   https://console.cloud.google.com/composer/environments/{self.environment}?project={self.project}")
        print(f"2. Trigger DAG manually or wait for schedule: {schedule_interval}")
        print(f"3. Monitor Dataproc jobs in:")
        print(f"   https://console.cloud.google.com/dataproc/jobs?project={self.project}")
        print(f"\nDAG name: {dag_name}")
        print(f"Environment: {self.environment}")
        print(f"DAG file: {dag_file}")
        
        return True


def main():
    parser = argparse.ArgumentParser(description="Deploy Agentic ETL to Cloud Composer")
    parser.add_argument("--project", help="GCP project ID", required=True)
    parser.add_argument("--location", help="GCP region", default="us-central1")
    parser.add_argument("--environment", help="Cloud Composer environment name", default="etl-prod")
    parser.add_argument("--dag-name", help="DAG name", default="agentic_etl_dag")
    parser.add_argument("--schedule", help="Schedule interval (cron)", default="0 2 * * *")
    parser.add_argument("--update", help="Update existing DAG", action="store_true")
    
    args = parser.parse_args()
    
    deployer = CloudComposerDeployer(
        project=args.project,
        location=args.location,
        environment=args.environment
    )
    
    success = deployer.deploy(
        dag_name=args.dag_name,
        schedule_interval=args.schedule
    )
    
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
